# Generated by Django 5.1.4 on 2025-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.TextField(max_length=10)),
                ('t_desc', models.TextField()),
                ('t_date', models.DateField()),
            ],
        ),
    ]
